/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group51.servicedeskproject.ui;

import com.group51.servicedeskproject.model.Role;
import com.group51.servicedeskproject.model.User;
import com.group51.servicedeskproject.service.TicketService;
import com.group51.servicedeskproject.service.UserService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Responsive Role Manager
 * @author tomwi
 */
public class ChangeRolesGUI extends javax.swing.JFrame {
    
    private javax.swing.JFrame parentFrame;
    private TicketService ticketService;
    private UserService userService;
    private User currentUser;
    
    // Cached lists to match table rows to actual database User objects
    private List<User> allUsersCache;
    private DefaultTableModel tableModel;
    
    public ChangeRolesGUI(javax.swing.JFrame parent, TicketService ticketService, UserService userService, User user) {
        this.parentFrame = parent;
        this.ticketService = ticketService;
        this.userService = userService;
        this.currentUser = user;
        initComponents();
        
        // Custom Table Initialization
        setupUserTable();
        populateUserTable();
        
        this.setLocationRelativeTo(null);
    }
    
    public ChangeRolesGUI() {
        initComponents();
    }
    
    private void setupUserTable() {
        // Define column headers for our clean UI layout
        String[] columnNames = {"Username", "Current Access Level"};
        
        // Prevent users from directly typing into the table grid cells
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        jTable1.setModel(tableModel);
        
        // Listen for selection changes: when a row is clicked, sync the dropdown choice
        jTable1.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                syncDropdownWithSelection();
            }
        });
    }
    
    private void populateUserTable() {
        tableModel.setRowCount(0); // Wipe stale data rows
        
        if (userService != null) {
            allUsersCache = userService.getAllUsers();
            for (User user : allUsersCache) {
                Object[] rowData = { user.getUsername(), user.getRole().name() };
                tableModel.addRow(rowData);
            }
        }
    }
    
    private void syncDropdownWithSelection() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1 && allUsersCache != null) {
            User selectedUser = allUsersCache.get(selectedRow);
            roleCombo.setSelectedItem(selectedUser.getRole().name());
        }
    }
    
    private void refreshTableData() {
        // 1. Get the underlying data model from your NetBeans JTable variable name
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // 2. Clear out all old rows so we don't append duplicates
        model.setRowCount(0);

        try {
            // 3. Fetch the fresh, updated list from your persistence layer pipeline
            java.util.List<com.group51.servicedeskproject.model.User> freshUserList = this.userService.getAllUsers();

            // 4. Re-populate the rows with the latest access levels
            if (freshUserList != null) {
                for (com.group51.servicedeskproject.model.User u : freshUserList) {
                    model.addRow(new Object[]{
                        u.getUsername(),
                        u.getRole() != null ? u.getRole().name() : "USER"
                    });
                }
            }
        } catch (Exception e) {
            System.err.println("Failed to pull fresh table data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox<>();
        btnRole = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 268;
        gridBagConstraints.ipady = 255;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Change role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 30, 0, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        roleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "WORKER", "USER" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        jPanel1.add(roleCombo, gridBagConstraints);

        btnRole.setText("Confirm");
        btnRole.addActionListener(this::btnRoleActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(btnRole, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUI mainMenu = new GUI(this, this.ticketService, this.userService, this.currentUser);
    
        mainMenu.setSize(this.getWidth(), this.getHeight());
        mainMenu.setLocation(this.getLocationOnScreen()); 
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoleActionPerformed
        // 1. Get the row selection index from the actual JTable variable name
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please select a user from the table first.", 
                "No Selection", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Read the username string from Column 0 of the highlighted row
        String targetUsername = jTable1.getValueAt(selectedRow, 0).toString();
    
        // 2. Grab the exact username string of the logged-in admin user
        String loggedInAdmin = (this.currentUser != null) ? this.currentUser.getUsername() : "";

        // 3. Self-Demotion Safety Check against the active session user context
        if (targetUsername.equals(loggedInAdmin)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Self-Demotion Lock: You cannot alter your own permissions directly via this screen panel.", 
                "Action Rejected", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Extract the selected target enum value from the correct JComboBox name
        Object selectedItem = roleCombo.getSelectedItem();
        if (selectedItem == null) {
            return;
        }

        com.group51.servicedeskproject.model.Role newRole;

        // Safely parse the value whether it's an explicit Role Enum or a standard String selection
        if (selectedItem instanceof com.group51.servicedeskproject.model.Role) {
            newRole = (com.group51.servicedeskproject.model.Role) selectedItem;
        } else {
            try {
                newRole = com.group51.servicedeskproject.model.Role.valueOf(selectedItem.toString().toUpperCase().trim());
            } catch (IllegalArgumentException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Invalid Role selection format type.", 
                    "Parsing Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // 5. Commit the change down to our persistence layer via the UserService instance
        try {
            this.userService.updateUserRole(targetUsername, newRole);

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Successfully updated permissions for " + targetUsername + " to [" + newRole.name() + "].",
                "Role Updated",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // =======================================================================
            // INSTANT REFRESH TRIGGER: Force the table view to reload immediately!
            // =======================================================================
            refreshTableData(); 

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database update failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRoleActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> roleCombo;
    // End of variables declaration//GEN-END:variables
}
