/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group51.servicedeskproject.ui;

import com.group51.servicedeskproject.service.TicketService;
import com.group51.servicedeskproject.model.Priority; // Adjust package path if needed
import com.group51.servicedeskproject.model.User;
import com.group51.servicedeskproject.service.UserService;

/**
 *
 * @author tomwi
 */
public class CreateTicket extends javax.swing.JFrame {
    
    private TicketService ticketService;
    private UserService userService;
    private User currentUser;

    // 3. Update the constructor to accept the service
    public CreateTicket(javax.swing.JFrame parentFrame, TicketService ticketService, User user) {
        this.ticketService = ticketService; // Store it for later use
        this.currentUser = user;
        initComponents(); // NetBeans GUI initialization
        
        this.setBounds(parentFrame.getBounds());
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int frameWidth = getContentPane().getWidth();
                int fieldWidth = Title_Enter.getWidth();
                int centerStartX = (frameWidth - fieldWidth) / 2;
                
                // FIXED TOP VERTICAL STARTING BOUND (Adjust 40/50 to shift higher or lower)
                int startY = 50; 
                int spacing = 22; // Tight spacing between fields for a cleaner layout
                
                ID_Title.setLocation(centerStartX, startY);
                ID_Enter.setLocation(centerStartX, ID_Title.getY() + spacing);
                
                Title_Title.setLocation(centerStartX, ID_Enter.getY() + spacing + 10);
                Title_Enter.setLocation(centerStartX, Title_Title.getY() + spacing);
                
                Description_Title.setLocation(centerStartX, Title_Enter.getY() + spacing + 10);
                Description_Enter.setLocation(centerStartX, Description_Title.getY() + spacing);
                
                Department_Title.setLocation(centerStartX, Description_Enter.getY() + spacing + 10);
                Department_Enter.setLocation(centerStartX, Department_Title.getY() + spacing);
                
                int createBtnX = (frameWidth - Update_Button.getWidth()) / 2;
                Update_Button.setLocation(createBtnX, Department_Enter.getY() + spacing + 15);
            }
        });
        
        if (this.ticketService != null) {
            int nextId = this.ticketService.getNextAvailableId();
            ID_Enter.setText(String.valueOf(nextId)); // Put your exact ID textfield name here
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateTicket.class.getName());

    /**
     * Creates new form Create_Ticket
     */
    public CreateTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Enter = new javax.swing.JTextField();
        ID_Title = new javax.swing.JLabel();
        Title_Title = new javax.swing.JLabel();
        Title_Enter = new javax.swing.JTextField();
        Description_Title = new javax.swing.JLabel();
        Description_Enter = new javax.swing.JTextField();
        Department_Title = new javax.swing.JLabel();
        Department_Enter = new javax.swing.JTextField();
        Update_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID_Enter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID_Enter.setText("Enter ID\n");
        ID_Enter.addActionListener(this::ID_EnterActionPerformed);

        ID_Title.setText("Ticket ID");

        Title_Title.setText("Ticket Title");

        Title_Enter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Title_Enter.setText("Enter title");
        Title_Enter.addActionListener(this::Title_EnterActionPerformed);

        Description_Title.setText("Ticket Descripton");

        Description_Enter.setText("Enter Description\n");

        Department_Title.setText("Ticket Department");

        Department_Enter.setText("Enter department");

        Update_Button.setText("Create");
        Update_Button.addActionListener(this::Update_ButtonActionPerformed);

        Back_Button.setText("Back");
        Back_Button.addActionListener(this::Back_ButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back_Button)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Description_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Description_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Department_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Department_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Update_Button)))
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(ID_Title))
                    .addComponent(Back_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Description_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Department_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Department_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_EnterActionPerformed

    private void Title_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Title_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Title_EnterActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // Pass the running service back so the main menu doesn't break
        GUI mainMenu = new GUI(this, this.ticketService, this.userService, this.currentUser);
        mainMenu.setSize(this.getWidth(), this.getHeight());
        mainMenu.setLocation(this.getLocationOnScreen()); 
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        // 1. Extract text from ALL four NetBeans GUI input fields
        // (Note: Change the txt variable names below to match your exact NetBeans inspector panel names)
        String idText = ID_Enter.getText().trim();
        String department = Department_Enter.getText().trim();
        String title = Title_Enter.getText().trim();
        String desc = Description_Enter.getText().trim();

        // 2. Comprehensive Input Validation (Ensuring no fields are sent blank)
        if (idText.isEmpty() || department.isEmpty() || title.isEmpty() || desc.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: All fields (ID, Department, Title, and Description) must be filled out.", 
                "Missing Information", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stops code execution immediately
        }

        // 3. Robust Data Type Verification (Ensuring the ID entered is an actual number)
        int ticketId = Integer.parseInt(ID_Enter.getText());
        try {
            ticketId = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: The Ticket ID must be a valid whole number (e.g., 101).", 
                "Invalid Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Stops execution if the user typed text into the ID field
        }
        
        if (this.ticketService != null && this.ticketService.isIdExists(ticketId)) {
            // Throw a warning dialogue pop-up message box alerting the user
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: A ticket with ID #" + ticketId + " already exists in the system.\nPlease choose a unique ID.",
                "Duplicate ID Found",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Kills execution instantly so the duplicate ticket is completely denied!
        }

        // 4. Connect to Backend: Pass all data directly to your team's TicketService
        // (Note: Adjust the method name/parameters to match your exact TicketService constructor requirements)
        // Add Priority.LOW right before the department variable
        this.ticketService.createTicket(ticketId, title, desc, Priority.LOW, department);

        // 5. User Feedback: Confirm submission success without shifting the screen
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Ticket #" + ticketId + " has been successfully logged!", 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // 6. Reset Form: Wipe out all inputs cleanly so a new ticket can be typed immediately
        CreateTicket createFrame = new CreateTicket(this, this.ticketService, this.currentUser); 
        createFrame.setSize(this.getWidth(), this.getHeight());
        createFrame.setLocation(this.getLocationOnScreen());
        createFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Update_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JTextField Department_Enter;
    private javax.swing.JLabel Department_Title;
    private javax.swing.JTextField Description_Enter;
    private javax.swing.JLabel Description_Title;
    private javax.swing.JTextField ID_Enter;
    private javax.swing.JLabel ID_Title;
    private javax.swing.JTextField Title_Enter;
    private javax.swing.JLabel Title_Title;
    private javax.swing.JButton Update_Button;
    // End of variables declaration//GEN-END:variables
}
