/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group51.servicedeskproject.ui;

import com.group51.servicedeskproject.model.Role;
import com.group51.servicedeskproject.model.User;
import com.group51.servicedeskproject.repository.DerbyUserRepository;
import com.group51.servicedeskproject.service.TicketService;
import com.group51.servicedeskproject.repository.UserRepository;
import com.group51.servicedeskproject.service.UserService;
import com.group51.servicedeskproject.service.SessionManager;
import database.DatabaseConnection;
import java.sql.SQLException;
import java.util.logging.Level;

/**
 * Responsive Service Desk Main Dashboard
 * @author tomwi
 */
public class GUI extends javax.swing.JFrame {
    
    private TicketService ticketService;
    private UserService userService;
    private User currentUser;

    public GUI(javax.swing.JFrame parentFrame, TicketService ticketService, UserService userService, User user) {
        this.ticketService = ticketService;
        this.userService = userService; 
        this.currentUser = user; 
        initComponents();
      
        
        applyRolePermissions();
        this.setLocationRelativeTo(null);
    }    
    
    // Constructor 2: Fixes the LoginScreen error (Accepts exactly 3 arguments)
    public GUI(TicketService ticketService, UserService userService, User user) {
        this.ticketService = ticketService;
        this.userService = userService; 
        this.currentUser = user; 
        initComponents();

        if (this.currentUser != null) {
            Role activeRole = this.currentUser.getRole();
            System.out.println("[GUI Handshake Check] Dashboard rendering for user: " 
                                + currentUser.getUsername() + " with active role: " + activeRole);
        }

        applyRolePermissions();

        this.setSize(new java.awt.Dimension(900, 650));
        this.setMinimumSize(new java.awt.Dimension(800, 600));
        
        this.setLocationRelativeTo(null);
    }

    // Constructor 3: Default fallback
    public GUI() {
        initComponents();
    }

    // 2. Add this security filter method at the bottom of your GUI class
    private void applyRolePermissions() {
        if (this.currentUser == null || this.currentUser.getRole() == null) {
            return;
        }
        
        if (this.btnChangeRoles != null) {
            this.btnChangeRoles.setVisible(true); 
        }

        // If the user is NOT an ADMIN, completely hide the administrative access button
        if (this.currentUser.getRole() != com.group51.servicedeskproject.model.Role.ADMIN) {
            if (this.btnChangeRoles != null) {
                this.btnChangeRoles.setVisible(false); 
            }

            // Optional: If you have a separate admin-only panel or tab, hide it here too:
            // if (this.adminPanel != null) { this.adminPanel.setVisible(false); }
        } else {
            // If they are an Admin, explicitly make sure it's visible
            if (this.btnChangeRoles != null) {
                this.btnChangeRoles.setVisible(true);
            }
        }

        // Rule: Admin can access absolutely everything (Leaves buttons enabled)
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnChangeRoles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton6.setText("Quit\n");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton2.setText("View Ticket");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton1.setText("Create Ticket\n");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ticket Service Desk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jButton6)
                .addGap(61, 61, 61))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        jButton3.setText("Log out");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        getContentPane().add(jButton3, gridBagConstraints);

        btnChangeRoles.setText("Roles");
        btnChangeRoles.addActionListener(this::btnChangeRolesActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(btnChangeRoles, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to exit the Service Desk System? Your progress will be saved.", 
            "Confirm Exit", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Create an instance of your CreateTicket frame
        CreateTicket createFrame = new CreateTicket(this, this.ticketService, this.currentUser); 
        createFrame.setSize(this.getWidth(), this.getHeight());
        createFrame.setLocation(this.getLocationOnScreen());
        createFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Revert to empty parentheses until your teammate adds the constructor to ViewTicket
        ViewTicket viewFrame = new ViewTicket(this, this.ticketService, this.userService, this.currentUser);
        viewFrame.setSize(this.getWidth(), this.getHeight());
        viewFrame.setLocation(this.getLocationOnScreen());
        viewFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SessionManager.clearSession();
        UserRepository userRepository =
                new DerbyUserRepository(DatabaseConnection.getInstance().getConnection());
        UserService freshUserService = new UserService(userRepository);
        LoginScreen freshLogin = new LoginScreen(this.ticketService, freshUserService);
        freshLogin.setLocationRelativeTo(null);
        freshLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnChangeRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeRolesActionPerformed
        if (currentUser.getRole() != Role.ADMIN) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Access Denied: You do not have permission to view or alter system roles.", 
                "Security Exception", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Terminate execution immediately so the next screen never instantiates
        }

        // Safe to open now because we verified they are an Admin!
        ChangeRolesGUI roleScreen = new ChangeRolesGUI(this, this.ticketService, this.userService, this.currentUser);
        roleScreen.setSize(this.getWidth(), this.getHeight());
        roleScreen.setLocation(this.getLocationOnScreen());
        roleScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChangeRolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeRoles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
