/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group51.servicedeskproject.ui;

import com.group51.servicedeskproject.service.TicketService;

/**
 *
 * @author tomwi
 */
public class Veiw_ticket extends javax.swing.JFrame {
    
    private TicketService ticketService; // Your backend pipeline connection

    // Constructor that receives the running backend service from the main GUI dashboard
    public Veiw_ticket(TicketService ticketService) {
        this.ticketService = ticketService;
        initComponents();
        populateTicketTable(); // Call this immediately to fill the table when opened!
    }

    // Keep the empty fallback constructor so NetBeans GUI builder is happy
    public Veiw_ticket() {
        initComponents();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Veiw_ticket.class.getName()); 

    
    private void populateTicketTable() {
        // DIAGNOSTIC 1: Check if the service database handed down is null
        if (this.ticketService == null) {
            System.out.println("❌ VIEW SCREEN SYSTEM CRITICAL: ticketService is NULL! Data pipeline handshake failed.");
            return;
        }

        System.out.println("🔄 VIEW SCREEN SYSTEM: Attempting to pull data out of backend tracking engine...");

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Explicitly redefine columns to wipe out NetBeans placeholder column headers
        model.setColumnIdentifiers(new Object[]{"ID", "Title", "Priority", "Status"});
        model.setRowCount(0); 

        int ticketCount = 0;

        // DIAGNOSTIC 2: Check if your backend collection loop is executing
        for (com.group51.servicedeskproject.model.Ticket t : this.ticketService.getTickets()) {
            model.addRow(new Object[]{
                t.getId(),
                t.getTitle(),
                t.getPriority(),
                "Open" // Replace with t.getStatus() if your model class tracks status!
            });
            ticketCount++;
        }

        System.out.println("✅ VIEW SCREEN SYSTEM: Successfully read and pasted " + ticketCount + " rows to the UI!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        statusConfirm = new javax.swing.JButton();
        priorityLabel = new javax.swing.JLabel();
        priorityConfirm = new javax.swing.JButton();
        getInfo = new javax.swing.JButton();
        comboStatus = new javax.swing.JComboBox<>();
        comboPriority = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("View Tickets");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(113, 113, 113)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(titleLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Update Status");

        statusConfirm.setText("Confirm");
        statusConfirm.addActionListener(this::statusConfirmActionPerformed);

        priorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priorityLabel.setText("Update Priority");

        priorityConfirm.setText("Confirm");
        priorityConfirm.addActionListener(this::priorityConfirmActionPerformed);

        getInfo.setText("Get Info");
        getInfo.addActionListener(this::getInfoActionPerformed);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPEN", "IN_PROGRESS", "CLOSED" }));

        comboPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOW", "MEDIUM", "HIGH", "CRITICAL" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(priorityConfirm)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(statusConfirm)
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboPriority, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(getInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priorityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 94, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(getInfo)
                .addGap(18, 18, 18)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusConfirm)
                .addGap(18, 18, 18)
                .addComponent(priorityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priorityConfirm)
                .addGap(24, 24, 24))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Description", "Department", "Priority", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (this.ticketService != null) {
            // Pass the live, running data back to the main menu frame!
            GUI mainMenu = new GUI(this.ticketService);
            mainMenu.setLocationRelativeTo(null);
            mainMenu.setVisible(true);

            // Close just this view window, keeping the background memory alive
            this.dispose();
        } else {
            System.out.println("Error: No live service instance found to return to main menu.");
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
    
        if (selectedRow != -1) {
            // Column 0 is ID, Column 1 is Title...
            // FIX: Change Priority column index from 3 to 2, and Status from 4 to 3!
            String priorityText = jTable1.getValueAt(selectedRow, 2).toString(); 
            String statusText   = jTable1.getValueAt(selectedRow, 3).toString(); 

            // Push the values directly into your sidebar text boxes
            comboStatus.setSelectedItem(statusText);   // Replaced .setText
            comboPriority.setSelectedItem(priorityText); // Priority text box
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void statusConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusConfirmActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a ticket from the list first.");
            return;
        }

        int ticketId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String newStatus = comboStatus.getSelectedItem().toString().trim();

        if (this.ticketService != null) {
            // 1. Fetch the actual, live ticket object from the backend engine
            com.group51.servicedeskproject.model.Ticket ticket = this.ticketService.getTicketById(ticketId);

            if (ticket != null) {
                try {
                    // 2. Convert display strings like "In-Progress" to match the strict uppercase enum "IN_PROGRESS"
                    String standardEnumString = newStatus.toUpperCase().replace("-", "_");

                    // 3. Update the ticket's internal status object
                    ticket.updateStatus(com.group51.servicedeskproject.model.Status.valueOf(standardEnumString));

                    // 4. Force update the visible table view cell instantly
                    jTable1.setValueAt(newStatus, selectedRow, 3);

                    javax.swing.JOptionPane.showMessageDialog(this, "Status updated successfully!");
                    populateTicketTable(); // Re-render table layout to show updates instantly

                } catch (IllegalArgumentException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Error: Selected status text does not match system enums.", 
                        "Status Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Ticket not found in backend engine.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_statusConfirmActionPerformed

    private void priorityConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityConfirmActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a ticket from the list first.");
            return;
        }

        int ticketId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String newPriorityStr = comboPriority.getSelectedItem().toString().trim().toUpperCase();

        if (this.ticketService != null) {
            try {
                // Match input string back to your team's Priority enum system
                com.group51.servicedeskproject.model.Priority selectedPriority = com.group51.servicedeskproject.model.Priority.valueOf(newPriorityStr);

                this.ticketService.updatePriority(ticketId, selectedPriority);

                javax.swing.JOptionPane.showMessageDialog(this, "Priority updated successfully!");
                populateTicketTable(); // Refresh UI layout display instantly
            } catch (IllegalArgumentException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Priority! Please type LOW, MEDIUM, or HIGH.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_priorityConfirmActionPerformed

    private void getInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInfoActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    
        // 1. Ensure a ticket is actually highlighted
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please select a ticket from the table menu first.", 
                "No Ticket Selected", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extract values directly from your table cells
        String ticketId    = jTable1.getValueAt(selectedRow, 0).toString();
        String title       = jTable1.getValueAt(selectedRow, 1).toString();
        String priority    = jTable1.getValueAt(selectedRow, 2).toString(); // Adjust column index if needed
        String status      = jTable1.getValueAt(selectedRow, 3).toString(); // Adjust column index if needed

        // 3. Look up the deep details (Description & Department) from your backend using the ID
        if (this.ticketService != null) {
            int id = Integer.parseInt(ticketId);

            // Find the exact ticket object in your backend engine
            // (Note: Adjust 'getTicketById' if your teammate named this method differently)
            com.group51.servicedeskproject.model.Ticket ticket = this.ticketService.getTicketById(id);

            if (ticket != null) {
                String description = ticket.getDescription();
                String department  = ticket.getDepartment();

                // 4. Build a beautiful multi-line message block
                String message = String.format(
                    "🎫 TICKET DETAILS (#%s)\n" +
                    "-------------------------------------\n" +
                    "🔹 Title: %s\n" +
                    "🏢 Department: %s\n" +
                    "⚠️ Priority: %s\n" +
                    "⚙️ Status: %s\n\n" +
                    "📝 DESCRIPTION:\n%s",
                    ticketId, title, department, priority, status, description
                );

                // 5. Throw it onto the screen in a scrollable or standard alert panel
                javax.swing.JOptionPane.showMessageDialog(this, 
                    message, 
                    "Ticket Extended Information", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_getInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Veiw_ticket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> comboPriority;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton getInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton priorityConfirm;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JButton statusConfirm;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
